[project]
name = "cska"
version = "0.1.0"
description = "Simple script to get PFC CSKA matches schedule in ics format"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "arrow>=1.4.0",
    "bs4>=0.0.2",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
]
